const mongoose = require('mongoose');

const EscalationHistorySchema = new mongoose.Schema({
    fromStatus: { type: String, required: true },
    toStatus: { type: String, required: true },
    changedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Profile', required: true },
    changedAt: { type: Date, default: Date.now },
    notes: { type: String, trim: true, maxlength: 500 },
}, { _id: false });

const EscalationSchema = new mongoose.Schema(
    {
        patientId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Profile',
            required: true,
            index: true,
        },
        caretakerId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Profile',
            index: true,
            description: 'Caretaker who raised or is related to the escalation',
        },
        organizationId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Organization',
            required: true,
            index: true,
        },
        assignedTo: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Profile',
            index: true,
            description: 'Care manager or admin who owns this escalation',
        },
        resolvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Profile',
        },

        // ── Classification ───────────────────────────────────────────
        type: {
            type: String,
            required: true,
            enum: [
                'missed_medication',
                'no_answer',
                'critical_medication',
                'adverse_reaction',
                'low_adherence',
                'medication_refill',
                'appointment_reminder',
                'emergency_contact',
                'fall_detected',
                'hospitalization',
                'patient_complaint',
                'caretaker_concern',
                'schedule_conflict',
                'other',
            ],
            index: true,
        },
        priority: {
            type: String,
            required: true,
            enum: ['low', 'medium', 'high', 'critical'],
            default: 'medium',
            index: true,
        },
        status: {
            type: String,
            required: true,
            enum: ['open', 'acknowledged', 'in_progress', 'resolved', 'closed', 'escalated'],
            default: 'open',
            index: true,
        },

        // ── Content ──────────────────────────────────────────────────
        message: {
            type: String,
            required: true,
            trim: true,
            maxlength: 2000,
        },
        resolution: {
            type: String,
            trim: true,
            maxlength: 2000,
        },
        resolvedAt: {
            type: Date,
        },

        // ── Related entities ─────────────────────────────────────────
        relatedCallLogId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'CallLog',
        },
        relatedMedicationId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Medication',
        },

        // ── Escalation chain ─────────────────────────────────────────
        escalatedFrom: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Escalation',
            description: 'Parent escalation if this was re-escalated',
        },
        escalationLevel: {
            type: Number,
            default: 1,
            min: 1,
            max: 5,
            description: '1=caretaker level, 2=care manager, 3=org admin, 4=super admin',
        },

        // ── History ──────────────────────────────────────────────────
        history: [EscalationHistorySchema],

        // ── SLA tracking ─────────────────────────────────────────────
        slaDeadline: {
            type: Date,
            description: 'When this escalation must be resolved by',
        },
        slaBreached: {
            type: Boolean,
            default: false,
        },

        // ── Auto-generated ───────────────────────────────────────────
        isAutoGenerated: {
            type: Boolean,
            default: false,
            description: 'True if system auto-generated (e.g., missed call auto-alert)',
        },
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Profile',
        },
    },
    {
        timestamps: true,
        toJSON: { virtuals: true },
        toObject: { virtuals: true },
    }
);

// ── Indexes ────────────────────────────────────────────────────
EscalationSchema.index({ organizationId: 1, status: 1, priority: -1 });
EscalationSchema.index({ assignedTo: 1, status: 1 });
EscalationSchema.index({ patientId: 1, status: 1 });
EscalationSchema.index({ caretakerId: 1, status: 1 });
EscalationSchema.index({ type: 1, status: 1, createdAt: -1 });
EscalationSchema.index({ slaDeadline: 1, slaBreached: 1 });

// ── Virtuals ───────────────────────────────────────────────────
EscalationSchema.virtual('isOpen').get(function () {
    return ['open', 'acknowledged', 'in_progress', 'escalated'].includes(this.status);
});

EscalationSchema.virtual('responseTime').get(function () {
    if (!this.history || this.history.length === 0) return null;
    const firstAck = this.history.find(h => h.toStatus === 'acknowledged');
    if (!firstAck) return null;
    return Math.round((firstAck.changedAt - this.createdAt) / (1000 * 60)); // minutes
});

EscalationSchema.virtual('resolutionTime').get(function () {
    if (!this.resolvedAt) return null;
    return Math.round((this.resolvedAt - this.createdAt) / (1000 * 60)); // minutes
});

// ── Pre-save ───────────────────────────────────────────────────
EscalationSchema.pre('save', function (next) {
    // Auto-set SLA deadline based on priority
    if (this.isNew && !this.slaDeadline) {
        const slaHours = { critical: 1, high: 4, medium: 24, low: 72 };
        const hours = slaHours[this.priority] || 24;
        this.slaDeadline = new Date(Date.now() + hours * 60 * 60 * 1000);
    }

    // Check SLA breach
    if (this.slaDeadline && !this.resolvedAt && new Date() > this.slaDeadline) {
        this.slaBreached = true;
    }

    next();
});

// ── Statics ────────────────────────────────────────────────────
EscalationSchema.statics.findOpenByOrganization = function (organizationId) {
    return this.find({
        organizationId,
        status: { $in: ['open', 'acknowledged', 'in_progress', 'escalated'] },
    })
        .populate('patientId', 'fullName avatarUrl')
        .populate('caretakerId', 'fullName')
        .populate('assignedTo', 'fullName')
        .sort({ priority: -1, createdAt: -1 });
};

EscalationSchema.statics.getEscalationStats = async function (organizationId, daysBack = 30) {
    const startDate = new Date(Date.now() - daysBack * 24 * 60 * 60 * 1000);

    return this.aggregate([
        {
            $match: {
                organizationId: new mongoose.Types.ObjectId(organizationId),
                createdAt: { $gte: startDate },
            },
        },
        {
            $group: {
                _id: {
                    type: '$type',
                    status: '$status',
                },
                count: { $sum: 1 },
            },
        },
        {
            $group: {
                _id: '$_id.type',
                total: { $sum: '$count' },
                statusBreakdown: {
                    $push: {
                        status: '$_id.status',
                        count: '$count',
                    },
                },
            },
        },
        { $sort: { total: -1 } },
    ]);
};

EscalationSchema.statics.findByAssignee = function (assignedTo, status = null) {
    const query = { assignedTo };
    if (status) {
        query.status = Array.isArray(status) ? { $in: status } : status;
    } else {
        query.status = { $in: ['open', 'acknowledged', 'in_progress'] };
    }
    return this.find(query)
        .populate('patientId', 'fullName avatarUrl')
        .populate('caretakerId', 'fullName')
        .sort({ priority: -1, createdAt: -1 });
};

// ── Instance methods ───────────────────────────────────────────
EscalationSchema.methods.acknowledge = function (userId) {
    this.history.push({ fromStatus: this.status, toStatus: 'acknowledged', changedBy: userId });
    this.status = 'acknowledged';
    this.assignedTo = this.assignedTo || userId;
    return this.save();
};

EscalationSchema.methods.resolve = function (userId, resolution) {
    this.history.push({ fromStatus: this.status, toStatus: 'resolved', changedBy: userId });
    this.status = 'resolved';
    this.resolvedBy = userId;
    this.resolvedAt = new Date();
    this.resolution = resolution;
    return this.save();
};

EscalationSchema.methods.escalateUp = function (userId, newAssignee, notes = '') {
    this.history.push({ fromStatus: this.status, toStatus: 'escalated', changedBy: userId, notes });
    this.status = 'escalated';
    this.assignedTo = newAssignee;
    this.escalationLevel = Math.min(this.escalationLevel + 1, 5);
    return this.save();
};

module.exports = mongoose.model('Escalation', EscalationSchema);
