import { StyleSheet, Platform } from 'react-native';

export const C = {
    bg: '#F4F7FB',
    surface: '#FFFFFF',
    primary: '#6366F1',
    primaryDark: '#4F46E5',
    primarySoft: '#EEF2FF',
    dark: '#1A202C',
    mid: '#4A5568',
    muted: '#94A3B8',
    border: '#E2E8F0',
    inputBg: '#FAFBFF',
    danger: '#EF4444',
    dangerBg: '#FEF2F2',
    success: '#22C55E',
    successBg: '#F0FDF4',
    successMid: '#16A34A',
    warning: '#F59E0B',
    warningBg: '#FFFBEB',
    tabTrack: '#E8EDF5',
};

export const FONT = {
    regular: { fontFamily: 'Inter_400Regular' },
    medium: { fontFamily: 'Inter_500Medium' },
    semibold: { fontFamily: 'Inter_600SemiBold' },
    bold: { fontFamily: 'Inter_700Bold' },
    heavy: { fontFamily: 'Inter_800ExtraBold' },
};

export const styles = StyleSheet.create({
    // ─── Outer shell ─────────────────────────────
    container: { flex: 1, backgroundColor: C.bg },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 48 },
    contentWrap: { paddingHorizontal: 24, paddingTop: 8, paddingBottom: 16 },

    // ─── Header row ──────────────────────────────
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 44,
        paddingBottom: 16,
        backgroundColor: C.bg,
    },
    backBtn: {
        width: 40, height: 40,
        borderRadius: 12,
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    stepCounter: {
        fontSize: 13,
        ...FONT.semibold,
        color: C.mid,
    },
    stepDots: {
        flexDirection: 'row',
        gap: 5,
        alignItems: 'center',
    },
    dot: {
        width: 6, height: 6,
        borderRadius: 3,
        backgroundColor: C.border,
    },
    dotActive: {
        backgroundColor: C.primary,
    },
    dotDone: {
        backgroundColor: C.primary,
        opacity: 0.5,
    },
    progressTrack: {
        height: 3,
        backgroundColor: C.border,
        marginHorizontal: 20,
        borderRadius: 2,
        marginBottom: 4,
    },
    progressFill: {
        height: 3,
        backgroundColor: C.primary,
        borderRadius: 2,
    },

    // ─── Pill badge ───────────────────────────────
    pillBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        backgroundColor: C.primarySoft,
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 7,
        marginBottom: 20,
        marginTop: 8,
        gap: 7,
    },
    pillDot: {
        width: 7, height: 7,
        borderRadius: 999,
        backgroundColor: C.primary,
    },
    pillBadgeText: {
        fontSize: 13,
        ...FONT.semibold,
        color: C.primary,
    },

    // ─── Step titles ──────────────────────────────
    stepTitleLine1: {
        fontSize: 30,
        ...FONT.heavy,
        color: C.dark,
        lineHeight: 36,
    },
    stepTitleLine2: {
        fontSize: 30,
        ...FONT.heavy,
        color: C.primary,
        lineHeight: 38,
        marginBottom: 28,
        letterSpacing: -0.5,
    },

    // ─── Form fields ──────────────────────────────
    fieldGroup: { marginBottom: 16 },
    label: {
        fontSize: 11,
        ...FONT.bold,
        color: C.mid,
        letterSpacing: 1.2,
        marginBottom: 8,
    },
    inputWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
        borderRadius: 14,
        height: 52,
        paddingHorizontal: 14,
        gap: 10,
    },
    inputFocused: {
        borderColor: C.primary,
        shadowColor: C.primary,
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
        elevation: 3,
    },
    inputError: {
        borderColor: C.danger,
        backgroundColor: C.dangerBg,
    },
    textInput: {
        flex: 1,
        fontSize: 15,
        ...FONT.medium,
        color: C.dark,
        paddingVertical: 0,
        height: '100%',
        includeFontPadding: false,
    },
    prefixText: {
        fontSize: 15,
        ...FONT.medium,
        color: C.mid,
    },

    // ─── Inline error ─────────────────────────────
    errorTextRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginTop: 6,
        marginLeft: 2,
    },
    fieldError: {
        fontSize: 12,
        ...FONT.medium,
        color: C.danger,
        flex: 1,
    },

    // ─── Block error ──────────────────────────────
    errorBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: C.dangerBg,
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#FCA5A5',
    },
    errorMsg: {
        color: '#991B1B',
        fontSize: 13,
        ...FONT.semibold,
        flex: 1,
    },
    warningBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
        backgroundColor: C.warningBg,
        borderRadius: 12,
        padding: 14,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#FEF3C7',
    },
    warningMsg: {
        color: '#92400E',
        fontSize: 13,
        ...FONT.medium,
        flex: 1,
        lineHeight: 20,
    },

    // ─── Buttons ──────────────────────────────────
    primaryBtn: {
        backgroundColor: C.primary,
        borderRadius: 14,
        height: 54,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
        shadowColor: C.primaryDark,
        shadowOpacity: 0.3,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
    },
    primaryBtnRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    primaryBtnText: {
        color: '#FFFFFF',
        fontSize: 16,
        ...FONT.bold,
    },
    outlineBtn: {
        backgroundColor: C.surface,
        borderRadius: 14,
        height: 54,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 12,
        borderWidth: 1.5,
        borderColor: C.border,
        marginTop: 8,
    },
    outlineBtnText: {
        fontSize: 15,
        ...FONT.semibold,
        color: C.dark,
    },

    // ─── Google btn ───────────────────────────────
    googleIconBox: {
        width: 26, height: 26,
        borderRadius: 7,
        backgroundColor: '#4285F4',
        alignItems: 'center',
        justifyContent: 'center',
    },
    googleIconText: {
        fontSize: 14,
        ...FONT.heavy,
        color: '#FFFFFF',
    },

    // ─── Divider ──────────────────────────────────
    dividerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 20,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: C.border,
    },
    dividerText: {
        marginHorizontal: 14,
        fontSize: 12,
        ...FONT.semibold,
        color: C.muted,
        letterSpacing: 0.5,
    },

    // ─── Password strength ────────────────────────
    strengthWrap: { marginTop: 8, paddingHorizontal: 2 },
    strengthBarRow: { flexDirection: 'row', gap: 4, marginBottom: 5 },
    strengthSeg: { flex: 1, height: 3, borderRadius: 2 },
    strengthLabel: { fontSize: 12, ...FONT.bold },

    // ─── Footer ───────────────────────────────────
    footer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 8,
        paddingBottom: 24,
    },
    footerText: {
        fontSize: 14,
        ...FONT.medium,
        color: C.mid,
    },
    footerLink: {
        fontSize: 14,
        ...FONT.heavy,
        color: C.primary,
    },

    // ─── Modals base ──────────────────────────────
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'flex-end',
    },
    modalOverlayCentered: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    otpModalCard: {
        backgroundColor: C.surface,
        borderRadius: 24,
        padding: 24,
        width: '100%',
        maxWidth: 400,
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 8 },
        elevation: 12,
    },
    modalSheet: {
        backgroundColor: C.surface,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        padding: 24,
        paddingBottom: 40,
        maxHeight: '92%',
    },
    modalHandle: {
        width: 40, height: 4,
        borderRadius: 2,
        backgroundColor: C.border,
        alignSelf: 'center',
        marginBottom: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        ...FONT.heavy,
        color: C.dark,
    },
    modalSub: {
        fontSize: 13,
        ...FONT.medium,
        color: C.muted,
        marginTop: 2,
    },
    closeBtnBox: {
        width: 36, height: 36,
        borderRadius: 10,
        backgroundColor: C.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ─── OTP modal ────────────────────────────────
    otpSubtext: {
        fontSize: 14,
        ...FONT.medium,
        color: C.mid,
        lineHeight: 22,
        marginBottom: 4,
    },
    resendRow: {
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 20,
    },
    timerText: { fontSize: 13, ...FONT.bold, color: C.muted },
    resendAction: { fontSize: 14, ...FONT.heavy, color: C.primary },
    attemptsText: {
        fontSize: 12,
        color: C.muted,
        textAlign: 'center',
        marginTop: 12,
    },

    // ─── UPI modal ────────────────────────────────
    paymentSummary: {
        backgroundColor: C.bg,
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        marginBottom: 20,
    },
    payPlanName: {
        fontSize: 12,
        ...FONT.bold,
        color: C.muted,
        textTransform: 'uppercase',
        letterSpacing: 1.2,
    },
    payAmount: {
        fontSize: 34,
        ...FONT.heavy,
        color: C.dark,
        marginTop: 4,
    },
    paySubtext: {
        fontSize: 13,
        ...FONT.bold,
        color: C.muted,
        marginBottom: 12,
    },
    upiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        backgroundColor: C.bg,
        borderRadius: 14,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: C.border,
    },
    upiIconBox: {
        width: 38, height: 38,
        borderRadius: 10,
        backgroundColor: C.surface,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    upiAppName: { flex: 1, fontSize: 15, ...FONT.semibold, color: C.dark },
    upiAction: { fontSize: 14, ...FONT.bold, color: C.primary },
    payDivider: { height: 1, backgroundColor: C.border, marginVertical: 16 },
    payManualBtn: {
        flexDirection: 'row',
        height: 54,
        borderRadius: 14,
        backgroundColor: C.dark,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    payManualText: { color: '#FFFFFF', fontSize: 15, ...FONT.bold },

    // ─── City selection (inline) ──────────────────
    citySearchWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        height: 52,
        marginBottom: 12,
    },
    citySearchInput: {
        flex: 1,
        fontSize: 15,
        ...FONT.medium,
        color: C.dark,
        paddingVertical: 0,
    },
    cityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 14,
        borderRadius: 12,
        marginBottom: 6,
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
    },
    cityRowActive: {
        borderColor: C.primary,
        backgroundColor: C.primarySoft,
    },
    cityName: { fontSize: 15, ...FONT.semibold, color: C.dark },
    cityState: { fontSize: 12, ...FONT.medium, color: C.muted, marginTop: 1 },
    radioOutline: {
        width: 20, height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: C.border,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 'auto',
    },
    radioActive: { borderColor: C.primary },
    radioDot: {
        width: 9, height: 9,
        borderRadius: 5,
        backgroundColor: C.primary,
    },

    // ─── Plan card ────────────────────────────────
    planCard: {
        borderRadius: 20,
        borderWidth: 2,
        borderColor: C.border,
        backgroundColor: C.surface,
        padding: 20,
        marginBottom: 12,
    },
    planCardActive: {
        borderColor: C.primary,
        backgroundColor: C.primarySoft,
        shadowColor: C.primary,
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
    },
    planHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 14,
    },
    planIconBox: {
        width: 48, height: 48,
        borderRadius: 14,
        backgroundColor: C.primarySoft,
        alignItems: 'center',
        justifyContent: 'center',
    },
    planTitle: { fontSize: 18, ...FONT.heavy, color: C.dark },
    planPrice: { fontSize: 22, ...FONT.heavy, color: C.primary, marginTop: 2 },
    planPriceSub: { fontSize: 13, ...FONT.medium, color: C.muted },
    planFeatures: { gap: 10, marginBottom: 18 },
    featureLine: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    featureText: { fontSize: 14, ...FONT.medium, color: C.mid },
    planActionBtn: {
        height: 46,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    planActionActive: { backgroundColor: C.primary },
    planActionInactive: { backgroundColor: C.bg, borderWidth: 1.5, borderColor: C.border },
    planActionTextActive: { color: '#FFFFFF', fontSize: 15, ...FONT.bold },
    planActionTextInactive: { color: C.mid, fontSize: 15, ...FONT.bold },
    explorerCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        padding: 16,
        borderRadius: 16,
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
        borderStyle: 'dashed',
        marginBottom: 12,
    },
    explorerText: { fontSize: 14, ...FONT.semibold, color: C.mid },
    explorerSub: { fontSize: 12, ...FONT.medium, color: C.muted, marginTop: 2 },

    // ─── Step indicator ───────────────────────────
    modernProgressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingVertical: 0,
    },
    stepDotWrap: { alignItems: 'center', width: 48 },
    stepLabelContainer: { height: 16, justifyContent: 'center', marginTop: 6 },
    stepDot: {
        width: 26, height: 26, borderRadius: 13,
        backgroundColor: C.surface,
        borderWidth: 1.5, borderColor: C.border,
        alignItems: 'center', justifyContent: 'center',
        zIndex: 2,
    },
    stepDotDone: { backgroundColor: C.primary, borderColor: C.primary },
    stepDotActive: {
        backgroundColor: C.primary, borderColor: C.primary,
        shadowColor: C.primary, shadowOpacity: 0.3,
        shadowRadius: 6, elevation: 4,
    },
    stepDotLabel: { fontSize: 12, ...FONT.bold, color: C.muted },
    stepNameLabel: { fontSize: 10, ...FONT.semibold, color: C.muted, textAlign: 'center' },
    stepConnector: {
        position: 'absolute', top: 13, left: 48, right: 48,
        height: 2, backgroundColor: C.border, zIndex: 1,
    },
    stepConnectorDone: { backgroundColor: C.primary },

    // ─── Success card (Step 4) ────────────────────
    successCard: {
        width: '100%',
        backgroundColor: C.surface,
        borderRadius: 20,
        padding: 28,
        alignItems: 'center',
        marginBottom: 16,
        borderWidth: 1,
        borderColor: C.border,
    },
    successCircle: {
        width: 88, height: 88, borderRadius: 44,
        backgroundColor: '#DCFCE7',
        alignItems: 'center', justifyContent: 'center',
        marginBottom: 16,
    },
    successTitle: { fontSize: 22, ...FONT.heavy, color: '#166534', textAlign: 'center' },
    successSubtitle: { fontSize: 15, ...FONT.medium, color: '#15803D', textAlign: 'center', marginTop: 6 },
    nextCard: {
        width: '100%',
        backgroundColor: C.surface,
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: C.border,
        marginBottom: 20,
    },
    nextCardTitle: { fontSize: 13, ...FONT.heavy, color: C.primary, letterSpacing: 1, marginBottom: 10 },
    nextCardDesc: { fontSize: 14, ...FONT.medium, color: C.mid, lineHeight: 20, marginBottom: 16 },
    journeyList: { gap: 12 },
    journeyItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    journeyIconBox: {
        width: 32, height: 32, borderRadius: 10,
        backgroundColor: C.primarySoft,
        alignItems: 'center', justifyContent: 'center',
    },
    journeyText: { fontSize: 14, ...FONT.semibold, color: C.dark, flex: 1 },

    // ─── Final/celebration (Step 5) ───────────────
    finalState: { alignItems: 'center', paddingBottom: 20, paddingTop: 10 },
    finalTitle: { fontSize: 28, ...FONT.heavy, color: C.dark, textAlign: 'center' },
    finalSub: {
        fontSize: 15, ...FONT.medium, color: C.mid,
        textAlign: 'center', marginTop: 10,
        paddingHorizontal: 20, lineHeight: 24,
    },
    finalCard: {
        width: '100%', backgroundColor: C.surface,
        borderRadius: 20, padding: 16,
        marginTop: 28, marginBottom: 28,
        gap: 10, borderWidth: 1, borderColor: C.border,
    },
    finalRow: {
        flexDirection: 'row', alignItems: 'center',
        gap: 14, padding: 14,
        backgroundColor: C.bg, borderRadius: 14,
    },
    finalIconBox: {
        width: 42, height: 42, borderRadius: 12,
        backgroundColor: C.primarySoft,
        alignItems: 'center', justifyContent: 'center',
    },
    finalCardTitle: { fontSize: 15, ...FONT.semibold, color: C.dark },
    finalCardText: { fontSize: 13, ...FONT.medium, color: C.muted, marginTop: 2 },

    // ─── Gender picker ────────────────────────────
    genderRow: { flexDirection: 'row', gap: 10, marginTop: 8 },
    genderBtn: {
        flex: 1, paddingVertical: 12, borderRadius: 12,
        backgroundColor: C.surface, borderWidth: 1.5, borderColor: C.border,
        alignItems: 'center',
    },
    genderBtnActive: { backgroundColor: C.primarySoft, borderColor: C.primary },
    genderBtnText: { fontSize: 14, ...FONT.semibold, color: C.mid },
    genderBtnTextActive: { color: C.primary },

    // ─── Processing state ─────────────────────────
    processingContainer: {
        paddingVertical: 60, alignItems: 'center',
        justifyContent: 'center', minHeight: 300,
    },
    processingTitle: {
        fontSize: 20, ...FONT.heavy, color: C.dark,
        marginTop: 28, textAlign: 'center',
    },
    processingSub: {
        fontSize: 14, ...FONT.medium, color: C.muted,
        textAlign: 'center', marginTop: 10,
        lineHeight: 22,
    },

    // ─── Location step ────────────────────────────
    detectBtn: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        height: 54, borderRadius: 14, backgroundColor: C.primary,
        gap: 10, marginBottom: 16,
        shadowColor: C.primaryDark, shadowOpacity: 0.3,
        shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 5,
    },
    detectBtnText: { color: '#FFFFFF', fontSize: 15, ...FONT.bold },
    locationToast: {
        flexDirection: 'row', alignItems: 'center', gap: 10,
        backgroundColor: C.successBg, padding: 14,
        borderRadius: 14, marginBottom: 16,
        borderWidth: 1, borderColor: '#DCFCE7',
    },
    locationToastText: { fontSize: 14, ...FONT.semibold, color: C.successMid, flex: 1 },

    // ─── Search modal (city) ──────────────────────
    searchWrap: {
        flexDirection: 'row', alignItems: 'center', gap: 10,
        backgroundColor: C.bg, borderRadius: 14,
        paddingHorizontal: 14, height: 48,
        borderWidth: 1, borderColor: C.border,
    },
    searchInput: { flex: 1, fontSize: 15, ...FONT.medium, color: C.dark, paddingVertical: 0 },
    emptyState: { alignItems: 'center', paddingVertical: 32 },
    emptyTitle: { fontSize: 15, ...FONT.semibold, color: C.mid, marginTop: 10 },
    emptyDesc: { fontSize: 13, ...FONT.medium, color: C.muted, textAlign: 'center', marginTop: 4 },
    cityOption: {
        flexDirection: 'row', alignItems: 'center',
        paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#F8FAFC',
    },
    cityOptionActive: { backgroundColor: '#F8FAFF' },
    cityIconBox: {
        width: 40, height: 40, borderRadius: 12,
        backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center',
    },
    cityStateText: { fontSize: 13, ...FONT.medium, color: C.muted, marginTop: 2 },

    // ─── hero (unused but kept for compat) ────────
    hero: { height: 0 },
    heroContent: {},
    heroLogoContainer: {},
    heroLabel: {},
    heroTitle: {},
    heroSubtitle: {},
    formCard: { paddingTop: 0, marginHorizontal: 0 },
    centerStepEnhanced: { alignItems: 'center', width: '100%' },

    // ─── Old compat aliases (referenced by existing step components) ──────────
    primaryBtnEnhanced: {
        backgroundColor: C.primary,
        borderRadius: 14,
        height: 54,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
        flexDirection: 'row',
        shadowColor: C.primaryDark,
        shadowOpacity: 0.28,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 5 },
        elevation: 5,
    },
    primaryBtnGradientEnhanced: {
        flex: 1, flexDirection: 'row', alignItems: 'center',
        justifyContent: 'space-between', paddingHorizontal: 20,
    },
    primaryBtnText: { color: '#FFFFFF', fontSize: 16, ...FONT.bold },
    googleBtnEnhanced: {
        flexDirection: 'row', height: 54, borderRadius: 14, backgroundColor: C.surface,
        borderWidth: 1.5, borderColor: C.border,
        alignItems: 'center', justifyContent: 'center', gap: 12, marginBottom: 16,
    },
    googleIconWrap: { width: 26, height: 26, alignItems: 'center', justifyContent: 'center' },
    googleTextG: { color: '#4285F4', fontSize: 18, fontWeight: 'bold' },
    googleBtnText: { fontSize: 15, ...FONT.semibold, color: C.dark },
    inputWrapEnhanced: {
        flexDirection: 'row', alignItems: 'center',
        backgroundColor: C.surface, borderWidth: 1.5, borderColor: C.border,
        borderRadius: 14, height: 52, paddingHorizontal: 14,
    },
    inputFocusedEnhanced: {
        borderColor: C.primary,
        shadowColor: C.primary, shadowOpacity: 0.1, shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 }, elevation: 3,
    },
    inputErrorEnhanced: { borderColor: C.danger, backgroundColor: C.dangerBg },
    textInputEnhanced: {
        flex: 1, paddingVertical: Platform.OS === 'ios' ? 14 : undefined,
        height: '100%', fontSize: 15, color: C.dark, ...FONT.medium,
        includeFontPadding: false,
    },
    textPrefixStyle: {
        fontSize: 15, color: C.mid, ...FONT.medium, marginRight: 4,
        paddingVertical: Platform.OS === 'ios' ? 14 : undefined,
    },
    rightIconWrap: { marginLeft: 8 },
    inlineIconBox: { width: 28, alignItems: 'center', justifyContent: 'center' },
    errorTextRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 6, marginLeft: 2 },
    fieldErrorEnhanced: { color: C.danger, fontSize: 12, ...FONT.medium },
    dividerRow: {
        flexDirection: 'row', alignItems: 'center', marginVertical: 18,
    },
    dividerLine: { flex: 1, height: 1, backgroundColor: C.border },
    dividerText: { marginHorizontal: 14, fontSize: 12, color: C.muted, ...FONT.semibold },
    footer: {
        flexDirection: 'row', justifyContent: 'center', alignItems: 'center',
        paddingHorizontal: 24, paddingBottom: 24, paddingTop: 8,
    },
    footerText: { fontSize: 14, color: C.mid, ...FONT.medium },
    footerAction: { fontSize: 14, ...FONT.heavy, color: C.primary },
    madeWith: { fontSize: 12, ...FONT.bold, color: C.border, marginTop: 16, textAlign: 'center' },
    errorBoxEnhanced: {
        flexDirection: 'row', gap: 10, backgroundColor: C.dangerBg,
        padding: 14, borderRadius: 14, marginBottom: 16,
        borderWidth: 1, borderColor: '#FCA5A5',
    },
    errorMsgEnhanced: { fontSize: 13, ...FONT.medium, flex: 1, color: '#991B1B', lineHeight: 20 },
    successCelebrationCard: {
        width: '100%', borderRadius: 20, padding: 28, alignItems: 'center', marginBottom: 16,
        backgroundColor: C.successBg, borderWidth: 1, borderColor: '#DCFCE7',
    },
    largeSuccessCircle: {
        width: 88, height: 88, borderRadius: 44, backgroundColor: '#DCFCE7',
        alignItems: 'center', justifyContent: 'center', marginBottom: 16,
    },
    successTitle: { fontSize: 22, ...FONT.heavy, color: '#166534', textAlign: 'center' },
    successSubtitle: { fontSize: 15, ...FONT.medium, color: '#15803D', textAlign: 'center', marginTop: 6 },
    nextStepsCard: {
        width: '100%', backgroundColor: C.surface, borderRadius: 20, padding: 20,
        borderWidth: 1, borderColor: C.border, marginBottom: 16,
    },
    nextStepsHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
    nextStepsTitle: { fontSize: 13, ...FONT.heavy, color: C.primary, letterSpacing: 1 },
    nextStepsDesc: { fontSize: 14, ...FONT.medium, color: C.mid, lineHeight: 20, marginBottom: 16 },
    journeyList: { gap: 12 },
    journeyItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    journeyIconBox: {
        width: 32, height: 32, borderRadius: 10,
        backgroundColor: C.primarySoft, alignItems: 'center', justifyContent: 'center',
    },
    journeyText: { fontSize: 14, ...FONT.semibold, color: C.dark, flex: 1 },
    finalState: { alignItems: 'center', paddingBottom: 20, paddingTop: 10 },
    successOrb: {
        width: 140, height: 140, borderRadius: 70, backgroundColor: C.primarySoft,
        alignItems: 'center', justifyContent: 'center', marginBottom: 24,
    },
    finalTitle: { fontSize: 28, ...FONT.heavy, color: C.dark, textAlign: 'center' },
    finalSub: {
        fontSize: 15, ...FONT.medium, color: C.mid, textAlign: 'center',
        marginTop: 10, paddingHorizontal: 20, lineHeight: 24,
    },
    finalCard: {
        width: '100%', backgroundColor: C.surface, borderRadius: 20, padding: 16,
        marginTop: 28, marginBottom: 28, gap: 10, borderWidth: 1, borderColor: C.border,
    },
    finalRow: {
        flexDirection: 'row', alignItems: 'center', gap: 14, padding: 14,
        backgroundColor: C.bg, borderRadius: 14,
    },
    finalIconBox: {
        width: 42, height: 42, borderRadius: 12,
        backgroundColor: C.primarySoft, alignItems: 'center', justifyContent: 'center',
    },
    finalCardTitle: { fontSize: 15, ...FONT.semibold, color: C.dark },
    finalCardText: { fontSize: 13, ...FONT.medium, color: C.muted, marginTop: 2 },
    genderBtn: {
        flex: 1, paddingVertical: 12, borderRadius: 12,
        backgroundColor: C.surface, borderWidth: 1.5, borderColor: C.border,
        alignItems: 'center',
    },
    genderBtnActive: { backgroundColor: C.primarySoft, borderColor: C.primary },
    genderBtnText: { fontSize: 14, ...FONT.semibold, color: C.mid },
    processingContainer: {
        paddingVertical: 60, alignItems: 'center', justifyContent: 'center', minHeight: 300,
    },
    processingTitle: { fontSize: 20, ...FONT.heavy, color: C.dark, marginTop: 28, textAlign: 'center' },
    processingSub: { fontSize: 14, ...FONT.medium, color: C.muted, textAlign: 'center', marginTop: 10, lineHeight: 22 },
    processingProgress: { marginTop: 32 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
    modalSheet: {
        backgroundColor: C.surface, borderTopLeftRadius: 28, borderTopRightRadius: 28,
        padding: 24, paddingBottom: 40, maxHeight: '92%', marginTop: 60,
    },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    modalTitle: { fontSize: 20, ...FONT.heavy, color: C.dark },
    modalSub: { fontSize: 13, ...FONT.medium, color: C.muted, marginTop: 2 },
    closeBtnBox: { width: 36, height: 36, borderRadius: 10, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' },
    otpSubtext: { fontSize: 14, ...FONT.medium, color: C.mid, lineHeight: 22 },
    resendRow: { alignItems: 'center', marginTop: 8, marginBottom: 20 },
    timerText: { fontSize: 13, ...FONT.bold, color: C.muted },
    resendAction: { fontSize: 14, ...FONT.heavy, color: C.primary },
    attemptsText: { fontSize: 12, color: C.muted, textAlign: 'center', marginTop: 12 },
    paymentSummary: { backgroundColor: C.bg, borderRadius: 16, padding: 20, alignItems: 'center', marginBottom: 20 },
    payPlanName: { fontSize: 12, ...FONT.bold, color: C.muted, textTransform: 'uppercase', letterSpacing: 1.2 },
    payAmount: { fontSize: 34, ...FONT.heavy, color: C.dark, marginTop: 4 },
    paySubtext: { fontSize: 13, ...FONT.bold, color: C.muted, marginBottom: 12 },
    upiRow: { flexDirection: 'row', alignItems: 'center', padding: 14, backgroundColor: C.bg, borderRadius: 14, marginBottom: 8, borderWidth: 1, borderColor: C.border },
    upiIconBox: { width: 38, height: 38, borderRadius: 10, backgroundColor: C.surface, alignItems: 'center', justifyContent: 'center', marginRight: 14 },
    upiAppName: { flex: 1, fontSize: 15, ...FONT.semibold, color: C.dark },
    upiAction: { fontSize: 14, ...FONT.bold, color: C.primary },
    payDivider: { height: 1, backgroundColor: C.border, marginVertical: 16 },
    payManualBtn: { flexDirection: 'row', height: 54, borderRadius: 14, backgroundColor: C.dark, alignItems: 'center', justifyContent: 'center', gap: 10 },
    payManualText: { color: '#FFFFFF', fontSize: 15, ...FONT.bold },
    searchWrap: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.bg, borderRadius: 14, paddingHorizontal: 14, height: 48, borderWidth: 1, borderColor: C.border },
    searchInput: { flex: 1, fontSize: 15, ...FONT.medium, color: C.dark, paddingVertical: 0 },
    emptyState: { alignItems: 'center', paddingVertical: 32 },
    emptyTitle: { fontSize: 15, ...FONT.semibold, color: C.mid, marginTop: 10 },
    emptyDesc: { fontSize: 13, ...FONT.medium, color: C.muted, textAlign: 'center', marginTop: 4 },
    cityOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#F8FAFC' },
    cityOptionActive: { backgroundColor: '#F8FAFF' },
    cityIconBox: { width: 40, height: 40, borderRadius: 12, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' },
    cityName: { fontSize: 15, ...FONT.semibold, color: C.dark, marginLeft: 14 },
    cityState: { fontSize: 13, ...FONT.medium, color: C.muted, marginTop: 2, marginLeft: 14 },
    radioOutline: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
    radioActive: { borderColor: C.primary },
    radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.primary },
    locationPrimaryBtn: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        height: 54, borderRadius: 14, backgroundColor: C.primary, gap: 10, marginBottom: 12,
        shadowColor: C.primaryDark, shadowOpacity: 0.28, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 5,
    },
    locationPrimaryBtnText: { color: '#FFFFFF', fontSize: 15, ...FONT.bold },
    locationSecondaryBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, gap: 8 },
    locationSecondaryBtnText: { fontSize: 14, ...FONT.bold, color: C.primary },
    locationSuccessToast: {
        flexDirection: 'row', alignItems: 'center', gap: 10,
        backgroundColor: '#F0FDF4', padding: 14, borderRadius: 14,
        marginBottom: 16, borderWidth: 1, borderColor: '#DCFCE7',
    },
    locationSuccessText: { fontSize: 14, ...FONT.semibold, color: '#15803D', flex: 1 },
    locationErrorText: { fontSize: 13, color: C.danger, ...FONT.medium, marginTop: 8, textAlign: 'center' },
    planCardGhost: {
        flexDirection: 'row', alignItems: 'center', gap: 14, padding: 16,
        borderRadius: 16, backgroundColor: C.bg, borderWidth: 1.5,
        borderColor: C.border, borderStyle: 'dashed', marginBottom: 12,
    },
    ghostIconWrap: {
        width: 42, height: 42, borderRadius: 12,
        backgroundColor: C.surface, alignItems: 'center', justifyContent: 'center',
    },
    planTitleGhost: { fontSize: 15, ...FONT.semibold, color: C.mid },
    planDesc: { fontSize: 13, ...FONT.medium, color: C.muted, marginTop: 2 },
    planCardEnhanced: {
        borderRadius: 20, marginBottom: 14, overflow: 'hidden',
        borderWidth: 2, borderColor: C.border, backgroundColor: C.surface,
    },
    planCardGradient: { padding: 22 },
    planCardHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 18 },
    planIconBoxEnhanced: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    planPriceCol: { flex: 1 },
    planTitleEnhanced: { fontSize: 18, ...FONT.heavy, color: C.dark },
    planPriceEnhanced: { fontSize: 24, ...FONT.heavy, color: C.primary, marginTop: 2 },
    planPriceSub: { fontSize: 13, ...FONT.medium, color: C.muted },
    selectedCheck: { width: 28, height: 28, borderRadius: 14, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center' },
    planFeaturesEnhanced: { gap: 10, marginBottom: 20 },
    featureLine: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    featureTextEnhanced: { fontSize: 14, ...FONT.medium, color: C.mid },
    planActionBtn: { height: 48, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    btnActive: { backgroundColor: C.primary },
    btnInactive: { backgroundColor: C.bg, borderWidth: 1, borderColor: C.border },
    txtActive: { color: '#FFFFFF', fontSize: 15, ...FONT.bold },
    txtInactive: { color: C.mid, fontSize: 15, ...FONT.bold },
    planActionBtnText: { fontSize: 15, ...FONT.bold },
    fieldGroup: { marginBottom: 16 },
    label: { fontSize: 11, ...FONT.bold, color: C.mid, letterSpacing: 1.2, marginBottom: 8 },
    strengthWrap: { marginTop: 8, paddingHorizontal: 2 },
    strengthBarRow: { flexDirection: 'row', gap: 4, marginBottom: 5 },
    strengthSeg: { flex: 1, height: 3, borderRadius: 2 },
    strengthLabel: { fontSize: 12, ...FONT.bold },
    verifyFieldRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    verifyBtnSmall: {
        height: 52, paddingHorizontal: 14, borderRadius: 14,
        backgroundColor: C.primarySoft, alignItems: 'center', justifyContent: 'center', marginTop: 19,
        borderWidth: 1, borderColor: C.primary,
    },
    verifiedBtn: { backgroundColor: '#DCFCE7', borderColor: '#22C55E' },
    verifyBtnText: { fontSize: 13, ...FONT.bold, color: C.primary },
});
